### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by joshuairwing** [joshuairwing/GCMS-Irwing-Joshua#2]
- [x] Instalar o Git localmente
- [ ] Criar projeto local
- [ ] Criar repositório local e realizar commits
- [ ] Subir alterações para o repositório remoto
- [ ] Fazer alterações no repositório da turma

@ramidedantas

**Comment by ramidedantas** [comment]
Manter issue aberta para quando for fazer as práticas de Git.
